name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check DATABASE secret
        run: |
          echo "DATABASE exists: ${{ secrets.DATABASE != '' }}"

      - name: Check Telegram bot token secret
        run: |
          echo "BOT exists: ${{ secrets.TELEGRAM_BOT_TOKEN != '' }}"

      - name: Check Telegram chat id secret
        run: |
          echo "CHAT exists: ${{ secrets.TELEGRAM_CHAT_ID != '' }}"
