name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "DATABASE exists: ${{ secrets.DATABASE != '' }}"
      - run: echo "BOT exists: ${{ secrets.TELEGRAM_BOT_TOKEN != '' }}"
      - run: echo "CHAT exists: ${{ secrets.TELEGRAM_CHAT_ID != '' }}"